# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

# ディレクトリをどこまで表示するか
[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

# ステージングされているファイルの数を表示
[git_status]
staged = '[++\($count\)](green)'
# 謎なやつ。どこで使われるんだろか
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
